//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AileHekimligiOtomasyonu.DAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muayene
    {
        public int MuayeneId { get; set; }
        public int DoktorId { get; set; }
        public int HastaId { get; set; }
        public int TaniId { get; set; }
        public int IlacId { get; set; }
        public string Sikayet { get; set; }
    
        public virtual Doktor Doktor { get; set; }
        public virtual Ilac Ilac { get; set; }
        public virtual Tani Tani { get; set; }
        public virtual Hasta Hasta { get; set; }
    }
}
